/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import suzanne from "../models/suzanne.glb";

export default function Suzanne({ ...props }) {
  const group = useRef()
  useFrame((state, delta) => (
    group.current.rotation.y += hovered ? 0.06 : 0.02,
    group.current.rotation.x += hovered ? 0.04 : 0.01
    ))
  const [hovered, hover] = useState(false)
  const { nodes, materials } = useGLTF(suzanne)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} onPointerOver={(event) => hover(true)}
      onPointerOut={(event) => hover(false)}/>
    </group>
  )
}
